#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define MODELS_CONF_CC2530_ZB500 1
#define BUTTON_SENSOR_CONF_ON 1
#define UIP_CONF_ICMP6        1

#define UDP_CLIENT_AUTOSTART  1

#endif /* PROJECT_CONF_H_ */
